# Generated by Django 5.0.6 on 2024-06-21 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0004_cidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='colaboradores',
            new_name='colaborares',
        ),
        migrations.AlterField(
            model_name='cidade',
            name='clima',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='faturamento',
            field=models.FloatField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interno.empresa')),
            ],
        ),
    ]
