# Generated by Django 5.0.6 on 2024-06-21 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0005_rename_colaboradores_empresa_colaborares_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='colaborares',
            new_name='colaboradores_total',
        ),
    ]
